import type { Worker } from "@/types/worker";

const gallery = [
  "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=900&q=80"
];

export const demoWorkers: Worker[] = [
  {
    id: "rajesh-electrician-delhi",
    userId: null,
    name: "Rajesh Kumar",
    category: "Electrician",
    categorySlug: "electrician",
    experienceYears: 8,
    rating: 4.8,
    reviewCount: 126,
    location: "Lajpat Nagar, Delhi",
    city: "Delhi",
    phone: "+919810001001",
    whatsapp: "919810001001",
    profilePhoto: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=600&q=80",
    shortDescription: "Fast home electrical repairs, new wiring, switchboards, and fan installation.",
    bio: "Rajesh handles residential electrical jobs across South Delhi with clear pricing and same-day visits whenever possible.",
    serviceDetails: ["Fan and light installation", "Switchboard repair", "Home wiring checks", "Inverter and MCB support"],
    gallery,
    availableToday: true,
    startingPrice: 249
  },
  {
    id: "imran-plumber-mumbai",
    userId: null,
    name: "Imran Shaikh",
    category: "Plumber",
    categorySlug: "plumber",
    experienceYears: 6,
    rating: 4.7,
    reviewCount: 91,
    location: "Andheri West, Mumbai",
    city: "Mumbai",
    phone: "+919820002002",
    whatsapp: "919820002002",
    profilePhoto: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=600&q=80",
    shortDescription: "Leak repair, tap replacement, bathroom fittings, and pipe blockage support.",
    bio: "Imran is trusted for neat plumbing work, practical diagnosis, and quick repairs for flats and shops.",
    serviceDetails: ["Leak detection", "Tap and shower fitting", "Drain blockage repair", "Kitchen and bathroom plumbing"],
    gallery,
    availableToday: true,
    startingPrice: 199
  },
  {
    id: "sunita-driver-bengaluru",
    userId: null,
    name: "Sunita Reddy",
    category: "Driver",
    categorySlug: "driver",
    experienceYears: 10,
    rating: 4.9,
    reviewCount: 143,
    location: "Indiranagar, Bengaluru",
    city: "Bengaluru",
    phone: "+919830003003",
    whatsapp: "919830003003",
    profilePhoto: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80",
    shortDescription: "Reliable personal driver for city rides, airport drops, and day bookings.",
    bio: "Sunita offers punctual driving services with local route knowledge and clean customer communication.",
    serviceDetails: ["Hourly bookings", "Airport transfer", "Outstation trips", "Family and office travel"],
    gallery,
    availableToday: false,
    startingPrice: 499
  },
  {
    id: "vijay-carpenter-pune",
    userId: null,
    name: "Vijay Pawar",
    category: "Carpenter Interior & Decorator",
    categorySlug: "carpenter",
    experienceYears: 12,
    rating: 4.8,
    reviewCount: 108,
    location: "Kothrud, Pune",
    city: "Pune",
    phone: "+919840004004",
    whatsapp: "919840004004",
    profilePhoto: "https://images.unsplash.com/photo-1615109398623-88346a601842?auto=format&fit=crop&w=600&q=80",
    shortDescription: "Furniture repairs, hinges, wardrobes, doors, and custom fittings.",
    bio: "Vijay works on home and office carpentry with sturdy finishing and careful measurements.",
    serviceDetails: ["Door and lock fitting", "Wardrobe repair", "Furniture assembly", "Custom shelves"],
    gallery,
    availableToday: true,
    startingPrice: 299
  },
  {
    id: "mohit-mechanic-jaipur",
    userId: null,
    name: "Mohit Sharma",
    category: "Mechanic Bike/Auto",
    categorySlug: "mechanic",
    experienceYears: 9,
    rating: 4.6,
    reviewCount: 77,
    location: "Malviya Nagar, Jaipur",
    city: "Jaipur",
    phone: "+919850005005",
    whatsapp: "919850005005",
    profilePhoto: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=600&q=80",
    shortDescription: "Bike and car checks, battery issues, servicing, and minor repairs.",
    bio: "Mohit supports vehicle owners with practical troubleshooting and transparent repair suggestions.",
    serviceDetails: ["Vehicle inspection", "Battery and starting issue", "Brake checks", "Routine servicing"],
    gallery,
    availableToday: true,
    startingPrice: 349
  },
  {
    id: "anil-painter-ahmedabad",
    userId: null,
    name: "Anil Patel",
    category: "Paint/Putty/POP",
    categorySlug: "painter",
    experienceYears: 7,
    rating: 4.5,
    reviewCount: 64,
    location: "Satellite, Ahmedabad",
    city: "Ahmedabad",
    phone: "+919860006006",
    whatsapp: "919860006006",
    profilePhoto: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&q=80",
    shortDescription: "Interior painting, rental touch-ups, wall putty, texture, and polishing.",
    bio: "Anil delivers clean painting work for apartments, shops, and quick pre-move touch-ups.",
    serviceDetails: ["Interior wall painting", "Texture paint", "Putty and primer", "Rental repaint"],
    gallery,
    availableToday: false,
    startingPrice: 599
  },
  {
    id: "farhan-ac-hyderabad",
    userId: null,
    name: "Farhan Ali",
    category: "AC/Cooler/Fridge/Washing Machine Repair",
    categorySlug: "ac-repair",
    experienceYears: 11,
    rating: 4.9,
    reviewCount: 152,
    location: "Gachibowli, Hyderabad",
    city: "Hyderabad",
    phone: "+919870007007",
    whatsapp: "919870007007",
    profilePhoto: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=600&q=80",
    shortDescription: "Split and window AC service, installation, gas refill, and cooling issues.",
    bio: "Farhan specializes in AC servicing and repairs with quick diagnosis for homes and small offices.",
    serviceDetails: ["AC wet service", "Gas refill", "Installation and uninstallation", "Cooling issue repair"],
    gallery,
    availableToday: true,
    startingPrice: 399
  }
];


